add sign_up, sign_in and change password for user
Skuuukaaa/Social_Network pull request #1
Opened 2021-07-14 13:40 UTC by Skuuukaaa

also added the bootstrap gem and smtp config for gmail

2021-07-15 19:52 UTC, b0nn1e requested changes

2021-07-15 19:52 UTC, b0nn1e commented on app/controllers/users_controller.rb
> +      flash[:notice] = 'Profile successfully updated'
Pleas, use i18n

2021-07-15 19:52 UTC, b0nn1e commented on app/views/devise/passwords/new.html.erb
> +</div>
New line missing

2021-07-15 19:52 UTC, b0nn1e commented on app/views/devise/passwords/edit.html.erb
> +<% content_for(:title, 'Settings') %>
Convert to haml or slim. Here and in other views.
See https://github.com/heartcombo/devise/wiki/How-To:-Create-Haml-and-Slim-Views

2021-07-15 19:52 UTC, b0nn1e commented on app/views/layouts/application.html.erb
> +    <a class="navbar-brand" href="#"><%=link_to  "Start Page", static_pages_home_path%></a>
Move "Start Page" and other to i18n

2021-07-15 19:52 UTC, b0nn1e commented on app/views/layouts/application.html.erb
> +        <%= link_to "English", { :locale=>'en' } %>
Use new syntax: `<%= link_to "English", { locale: 'en' } %>`

2021-07-15 19:52 UTC, b0nn1e commented on app/views/layouts/static_pages.html.erb
> +<!DOCTYPE html>
If it's possible, avoid using several layouts

2021-07-15 19:52 UTC, b0nn1e commented on config/environments/development.rb
> +    user_name: 'mgorb71@gmail.com',
Put credential to secrets

2021-07-15 19:52 UTC, b0nn1e commented on config/application.yml.sample
> +  GOOGLE_CLIENT_ID: "209716765770-2l5bumj7s635mts1bo2had8bfidpt29g.apps.googleusercontent.com"
Move it to credentials too.

2021-07-15 19:52 UTC, b0nn1e commented on test/controllers/omniauth_callbacks_controller_test.rb
> +# frozen_string_literal: true
Remove `test` folder.
Please add Rspec and configure generators https://stackoverflow.com/a/22400845/3753977

2021-07-19 09:59 UTC, ih-andrey-andreev commented on db/migrate/20210719092529_add_user_first_and_second_name_to_users.rb
> +    add_column :users, :user_first_name, :string
Mb just "first_name"?

2021-07-19 10:04 UTC, Skuuukaaa commented on db/migrate/20210719092529_add_user_first_and_second_name_to_users.rb
> +    add_column :users, :user_first_name, :string
ok

2021-07-20 09:29 UTC, b0nn1e commented on app/controllers/users_controller.rb
> +      # redirect_to user_path(@user)
Uncomment it?

2021-07-20 09:30 UTC, b0nn1e commented on app/helpers/omniauth_callbacks_helper.rb
> +# frozen_string_literal: true
You can remove empty helpers files. 
Also, you can configure rails generator to skip generate helpers

2021-07-20 09:31 UTC, b0nn1e commented on app/mailers/application_mailer.rb
> +  default from: 'mgorb71@gmail.com'
Get it from secrets

2021-07-20 10:10 UTC, Skuuukaaa commented on config/environments/production.rb
> +  config.action_mailer.smtp_settings = {
Maksim
add rspec and config generators, delete folder test, put credential (smtp settings and googleoauth)
https://github.com/Skuuukaaa/Social_Network/pull/1/commits/b545e30093a4413e41b872224535b0906ac4677a
maybe, you watched the old commit?)

2021-07-20 10:12 UTC, Skuuukaaa commented on app/controllers/users_controller.rb
> +      # redirect_to user_path(@user)
in the next pull request uncomment it

2021-07-20 22:37 UTC, b0nn1e approved these changes

2021-07-21 07:05 UTC, merged